# Generated by Django 3.2 on 2024-10-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type_name', models.CharField(default='', max_length=100, verbose_name='账号类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '账号类型',
                'db_table': 'accountmanagement_account_type',
            },
        ),
        migrations.CreateModel(
            name='AccountManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='账号类型描述')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='账号数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accountmanagement.accounttype', verbose_name='账号类型')),
            ],
            options={
                'verbose_name': '账号记录管理',
                'db_table': 'accountmanagement_account_manage',
            },
        ),
    ]
