# Generated by Django 3.2 on 2024-10-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmanage',
            options={},
        ),
        migrations.RemoveField(
            model_name='accountmanage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accountmanage',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='accountmanage',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountmanagement.accounttype'),
        ),
        migrations.AlterField(
            model_name='accountmanage',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='accountmanage',
            name='description',
            field=models.CharField(choices=[('模板', '模板'), ('账号记录', '账号记录')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='accountmanage',
            table=None,
        ),
    ]
