# Generated by Django 3.2 on 2024-11-20 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
