# Generated by Django 3.2 on 2024-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0002_auto_20241120_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='yaml_file',
            field=models.TextField(default='', verbose_name='Yaml文件'),
        ),
    ]
