# Generated by Django 3.2 on 2024-09-20 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='名称')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='标识')),
                ('parent', models.IntegerField(verbose_name='父级ID')),
                ('level', models.IntegerField(verbose_name='层级')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='tag标签')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '服务树',
                'verbose_name_plural': '服务树',
                'db_table': 'tree_list',
            },
        ),
        migrations.CreateModel(
            name='TreeRelatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.IntegerField(verbose_name='服务树节点ID')),
                ('target_id', models.IntegerField(verbose_name='资源ID')),
                ('type', models.IntegerField(verbose_name='资源类型')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '服务树资源关联表',
                'verbose_name_plural': '服务树资源关联表',
                'db_table': 'tree_related',
            },
        ),
    ]
