# Generated by Django 3.2 on 2024-09-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_hostdetails_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostdetails',
            name='description',
        ),
    ]
