# Generated by Django 3.2 on 2024-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_hostprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostprocess',
            name='argvs',
            field=models.TextField(default='', null=True, verbose_name='进程参数'),
        ),
    ]
