# Generated by Django 3.2 on 2024-09-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_alter_hostprocess_argvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ip', models.CharField(default='', max_length=128, null=True, verbose_name='本地IP')),
                ('local_port', models.CharField(default='', max_length=128, null=True, verbose_name='本地端口')),
                ('remote_ip', models.CharField(default='', max_length=128, null=True, verbose_name='远程IP')),
                ('remote_port', models.CharField(default='', max_length=128, null=True, verbose_name='远程端口')),
                ('process', models.CharField(default='', max_length=128, null=True, verbose_name='进程')),
                ('pid', models.CharField(default='', max_length=128, null=True, verbose_name='进程ID')),
                ('state', models.CharField(default='', max_length=128, null=True, verbose_name='进程状态')),
                ('protocol', models.CharField(default='', max_length=128, null=True, verbose_name='协议')),
                ('related_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.hostdetails', to_field='agent_id', verbose_name='关联的主机详情')),
            ],
            options={
                'verbose_name': '主机端口信息',
                'verbose_name_plural': '主机端口信息',
                'db_table': 'cmdb_host_port',
            },
        ),
    ]
