# Generated by Django 3.2 on 2024-09-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_hostport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostport',
            name='local_ip',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='本地IP'),
        ),
        migrations.AlterField(
            model_name='hostport',
            name='local_port',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='本地端口'),
        ),
        migrations.AlterField(
            model_name='hostport',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程ID'),
        ),
        migrations.AlterField(
            model_name='hostport',
            name='process',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程'),
        ),
        migrations.AlterField(
            model_name='hostport',
            name='protocol',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='协议'),
        ),
        migrations.AlterField(
            model_name='hostport',
            name='remote_ip',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='远程IP'),
        ),
        migrations.AlterField(
            model_name='hostport',
            name='remote_port',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='远程端口'),
        ),
        migrations.AlterField(
            model_name='hostport',
            name='state',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程状态'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='argvs',
            field=models.TextField(blank=True, default='', null=True, verbose_name='进程参数'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='cmd',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程命令'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='egroup',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程组'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程名称'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程ID'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='ppid',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='父进程ID'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程优先级'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='session',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程会话ID'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='size',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程实际内存大小'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='state',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程状态'),
        ),
        migrations.AlterField(
            model_name='hostprocess',
            name='vm_size',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='进程虚拟内存大小'),
        ),
    ]
