# Generated by Django 3.2 on 2024-09-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20240923_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageManage',
        ),
    ]
