# Generated by Django 3.2 on 2024-09-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='镜像名称')),
                ('num_images', models.IntegerField(default=0, verbose_name='镜像数量')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
                ('path', models.CharField(default='', max_length=128, verbose_name='镜像路径')),
                ('domain_name', models.CharField(default='', max_length=128, verbose_name='域名')),
                ('namespace', models.CharField(default='', max_length=128, verbose_name='命名空间')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='镜像标签')),
            ],
            options={
                'db_table': 'imagemanagement_image_manage',
            },
        ),
    ]
