# Generated by Django 3.2 on 2024-10-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagemanagement', '0002_auto_20240923_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemanage',
            name='region',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='区域'),
        ),
    ]
